# FX data retrieval

Steps: 

1. Load 1-Minute data from https://github.com/philipperemy/FX-1-Minute-Data (there is a link to Google Disk)
2. Extract all CSV-s from zip files
3. Create one dataframe, pivot and clean it
4. Save to parquet

In [9]:
import os
import sys
import warnings

sys.path.append("..")

In [1]:
import glob
import pandas as pd
import numpy as np
import zipfile

from tqdm import tqdm

In [130]:
%load_ext autoreload
%autoreload 2

from rl_trading.features.tech_inidicators import compute_technical_indicators

## Raw data extraction

In [2]:
datafolder = "C:/Users/Ivan/Downloads/"

In [3]:
list_of_files = glob.glob(f"{datafolder}*.zip")

In [4]:
list_of_files

['C:/Users/Ivan/Downloads\\eurjpy-20260128T175233Z-3-001.zip',
 'C:/Users/Ivan/Downloads\\eurusd-20260128T175054Z-3-001.zip',
 'C:/Users/Ivan/Downloads\\sgdjpy-20260128T175337Z-3-001.zip',
 'C:/Users/Ivan/Downloads\\usdjpy-20260128T175245Z-3-001.zip',
 'C:/Users/Ivan/Downloads\\usdsgd-20260128T182254Z-3-001.zip']

In [11]:
raw_results = []

for file in tqdm(list_of_files):

    upper_layer = zipfile.ZipFile(file)
    ccy = file.split("\\")[1][:6]

    for inner_file in upper_layer.namelist():

        inner_file = zipfile.ZipFile(upper_layer.extract(inner_file))

        for innermost_file in inner_file.namelist():

            if innermost_file[-3:] == "csv":
                temp = pd.read_csv(
                    inner_file.extract(innermost_file), sep=";", header=None
                )
                temp.columns = ["timestamp", "open", "high", "low", "close", "volume"]
                temp["ccy"] = ccy
                raw_results.append(temp.copy())

        inner_file.close()

    upper_layer.close()

100%|████████████████████████████████████████████████████████████████████████████████████| 5/5 [02:00<00:00, 24.01s/it]

## Data cleaning

In [24]:
results_df = pd.concat(raw_results, ignore_index=True)

In [25]:
results_df.head()

         timestamp     open     high      low    close  volume     ccy
0  20240101 170600  155.555  155.555  155.555  155.555       0  eurjpy
1  20240101 170700  155.565  155.566  155.540  155.566       0  eurjpy
2  20240101 170800  155.540  155.566  155.540  155.566       0  eurjpy
3  20240101 170900  155.566  155.566  155.566  155.566       0  eurjpy
4  20240101 171000  155.539  155.565  155.539  155.565       0  eurjpy

In [26]:
%%time
results_df["timestamp"] = pd.to_datetime(
    results_df["timestamp"], format="%Y%m%d %H%M%S"
)

CPU times: total: 2min 9s
Wall time: 2min 10s

Lets leave data only from 2015 (last 10 years)

In [30]:
results_df = results_df.loc[results_df.timestamp >= "2015-01-01",]

Leaving workdays and trading hours only

#### Lets check that we will not affect data from different markets by filtering by hour

Thats how we would do it. Unfortunately, volume data is not saved in source

In [62]:
results_df["hour"] = results_df.timestamp.dt.hour

In [36]:
results_df["weekday_hour"] = (
    results_df.timestamp.dt.weekday + 1
) * results_df.timestamp.dt.hour

In [76]:
results_df["date"] = results_df.timestamp.dt.date

In [38]:
(
    results_df.groupby(["ccy", "date", "weekday_hour"])
    .agg({"volume": sum})
    .reset_index()
    .groupby(["ccy", "weekday_hour"])
    .agg({"volume": "mean"})
)

C:\Users\Ivan\AppData\Local\Temp\ipykernel_2228\1643465873.py:4: FutureWarning: The provided callable <built-in function sum> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  .agg({"volume": sum})

                     volume
ccy    weekday_hour
eurjpy 0                0.0
       1                0.0
       2                0.0
       3                0.0
       4                0.0
...                     ...
usdsgd 133              0.0
       140              0.0
       147              0.0
       154              0.0
       161              0.0

[366 rows x 1 columns]

#### So lets assume that trading hours are 9.00 - 19.00 

(All times are reported in the same timezone as said in the source)

In [39]:
results_df = results_df.loc[results_df.timestamp.dt.weekday <= 4, :]

In [40]:
results_df = results_df.loc[
    (results_df.timestamp.dt.hour < 19) & (results_df.timestamp.dt.hour >= 9), :
]

In [41]:
results_df.shape

(7157509, 9)

### No missing data in cells

In [59]:
results_df.dropna().shape[0] == results_df.shape[0]

True

### Lets turn it into hourly data

In [68]:
results_df = (
    results_df.groupby(["date", "hour", "ccy"])
    .agg({"open": "first", "high": max, "low": min, "close": "last"})
    .reset_index()
    .assign(
        timestamp=lambda df: pd.to_datetime(
            df["date"].astype(str) + " " + df["hour"].astype(str) + ":00:00",
            format="%Y-%m-%d %H:%M:%S",
        )
    )
)

C:\Users\Ivan\AppData\Local\Temp\ipykernel_2228\1010845058.py:4: FutureWarning: The provided callable <built-in function max> is currently using SeriesGroupBy.max. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "max" instead.
  .agg(
C:\Users\Ivan\AppData\Local\Temp\ipykernel_2228\1010845058.py:4: FutureWarning: The provided callable <built-in function min> is currently using SeriesGroupBy.min. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "min" instead.
  .agg(

In [124]:
results_df = results_df.sort_values(["ccy", "timestamp"])

In [125]:
results_df["dt"] = results_df.groupby(["ccy", "date"])["timestamp"].diff()
results_df["dt"] = results_df["dt"].dt.total_seconds() / 3600

In [126]:
results_df.groupby(["ccy"])["dt"].value_counts()

ccy     dt
eurjpy  1.0    21338
        2.0      307
        3.0       47
        4.0        3
eurusd  1.0    21354
        2.0      317
        3.0       44
        4.0        1
sgdjpy  1.0    21324
        2.0      296
        3.0       57
        4.0        2
        5.0        1
        6.0        1
usdjpy  1.0    21333
        2.0      322
        3.0       43
        4.0        1
usdsgd  1.0    21334
        2.0      325
        3.0       34
        4.0        2
Name: count, dtype: int64

In [127]:
results_df.shape

(121496, 8)

We will assume that price does not change during larger pauses

### And add features

In [141]:
enhanced_data_storage = []

for ccy, one_ccy_data in results_df.groupby("ccy"):
    enhanced_data = compute_technical_indicators(df=one_ccy_data)
    enhanced_data_storage.append(enhanced_data.copy())

In [145]:
final_data = pd.concat(enhanced_data_storage, ignore_index=True).dropna()

In [148]:
final_data = (
    final_data.drop(columns=["date", "dt"])
    .sort_values(["ccy", "timestamp"])
    .reset_index(drop=True)
)

In [150]:
final_data.to_parquet("../data/FX_data.parquet.gzip", compression="gzip")